
package ua.mega.staffmanagement;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "employeeManagementWebService", targetNamespace = "http://staffmanagement.mega.ua/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeManagementWebService {


    /**
     * 
     * @return
     *     returns java.util.List<ua.mega.staffmanagement.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllEmployees", targetNamespace = "http://staffmanagement.mega.ua/", className = "ua.mega.staffmanagement.GetAllEmployees")
    @ResponseWrapper(localName = "getAllEmployeesResponse", targetNamespace = "http://staffmanagement.mega.ua/", className = "ua.mega.staffmanagement.GetAllEmployeesResponse")
    @Action(input = "http://staffmanagement.mega.ua/employeeManagementWebService/getAllEmployeesRequest", output = "http://staffmanagement.mega.ua/employeeManagementWebService/getAllEmployeesResponse")
    public List<Employee> getAllEmployees();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registerEmployee", targetNamespace = "http://staffmanagement.mega.ua/", className = "ua.mega.staffmanagement.RegisterEmployee")
    @ResponseWrapper(localName = "registerEmployeeResponse", targetNamespace = "http://staffmanagement.mega.ua/", className = "ua.mega.staffmanagement.RegisterEmployeeResponse")
    @Action(input = "http://staffmanagement.mega.ua/employeeManagementWebService/registerEmployeeRequest", output = "http://staffmanagement.mega.ua/employeeManagementWebService/registerEmployeeResponse")
    public void registerEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ua.mega.staffmanagement.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchBySurname", targetNamespace = "http://staffmanagement.mega.ua/", className = "ua.mega.staffmanagement.SearchBySurname")
    @ResponseWrapper(localName = "searchBySurnameResponse", targetNamespace = "http://staffmanagement.mega.ua/", className = "ua.mega.staffmanagement.SearchBySurnameResponse")
    @Action(input = "http://staffmanagement.mega.ua/employeeManagementWebService/searchBySurnameRequest", output = "http://staffmanagement.mega.ua/employeeManagementWebService/searchBySurnameResponse")
    public List<Employee> searchBySurname(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ua.mega.staffmanagement.Employee
     * @throws EmployeeNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeById", targetNamespace = "http://staffmanagement.mega.ua/", className = "ua.mega.staffmanagement.GetEmployeeById")
    @ResponseWrapper(localName = "getEmployeeByIdResponse", targetNamespace = "http://staffmanagement.mega.ua/", className = "ua.mega.staffmanagement.GetEmployeeByIdResponse")
    @Action(input = "http://staffmanagement.mega.ua/employeeManagementWebService/getEmployeeByIdRequest", output = "http://staffmanagement.mega.ua/employeeManagementWebService/getEmployeeByIdResponse", fault = {
        @FaultAction(className = EmployeeNotFoundException_Exception.class, value = "http://staffmanagement.mega.ua/employeeManagementWebService/getEmployeeById/Fault/EmployeeNotFoundException")
    })
    public Employee getEmployeeById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws EmployeeNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws EmployeeNotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteEmployeeById", targetNamespace = "http://staffmanagement.mega.ua/", className = "ua.mega.staffmanagement.DeleteEmployeeById")
    @ResponseWrapper(localName = "deleteEmployeeByIdResponse", targetNamespace = "http://staffmanagement.mega.ua/", className = "ua.mega.staffmanagement.DeleteEmployeeByIdResponse")
    @Action(input = "http://staffmanagement.mega.ua/employeeManagementWebService/deleteEmployeeByIdRequest", output = "http://staffmanagement.mega.ua/employeeManagementWebService/deleteEmployeeByIdResponse", fault = {
        @FaultAction(className = EmployeeNotFoundException_Exception.class, value = "http://staffmanagement.mega.ua/employeeManagementWebService/deleteEmployeeById/Fault/EmployeeNotFoundException")
    })
    public void deleteEmployeeById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws EmployeeNotFoundException_Exception
    ;

}
