
package ua.mega.urm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://www.mega.ua/urm")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param getUserByIdRequest
     * @return
     *     returns ua.mega.urm.GetUserByIdResponse
     */
    @WebMethod
    @WebResult(name = "getUserByIdResponse", targetNamespace = "http://www.mega.ua/urm", partName = "getUserByIdResponse")
    public GetUserByIdResponse getUserById(
        @WebParam(name = "getUserByIdRequest", targetNamespace = "http://www.mega.ua/urm", partName = "getUserByIdRequest")
        GetUserByIdRequest getUserByIdRequest);

}
